site_name: Rebel Notifications
site_description: Matomo plugin for custom notifications
repo_url: https://github.com/Digitalist-Open-Cloud/Matomo-Plugin-RebelNotifications
theme:
  name: readthedocs
  highlightjs: true
  user_color_mode_toggle: true
markdown_extensions:
  - admonition

nav:
  - Overview:
      - Usage: index.md
  - FAQ:
      - Frequently Asked Questions: faq.md
